config/routes.rb
Rails.application.routes.draw do
  resources :rings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ring.rb
class Ring < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  before_action :set_ring, only: [:show, :edit, :update, :destroy]

  # GET /rings
  # GET /rings.json
  def index
    @rings = Ring.all
  end

  # GET /rings/1
  # GET /rings/1.json
  def show
  end

  # GET /rings/new
  def new
    @ring = Ring.new
  end

  # GET /rings/1/edit
  def edit
  end

  # POST /rings
  # POST /rings.json
  def create
    @ring = Ring.new(ring_params)

    respond_to do |format|
      if @ring.save
        format.html { redirect_to @ring, notice: 'Ring was successfully created.' }
        format.json { render :show, status: :created, location: @ring }
      else
        format.html { render :new }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rings/1
  # PATCH/PUT /rings/1.json
  def update
    respond_to do |format|
      if @ring.update(ring_params)
        format.html { redirect_to @ring, notice: 'Ring was successfully updated.' }
        format.json { render :show, status: :ok, location: @ring }
      else
        format.html { render :edit }
        format.json { render json: @ring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rings/1
  # DELETE /rings/1.json
  def destroy
    @ring.destroy
    respond_to do |format|
      format.html { redirect_to rings_url, notice: 'Ring was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ring
      @ring = Ring.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ring_params
      params.require(:ring).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repairs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rings/_form.html.erb
<%= form_for(ring) do |f| %>
  <% if ring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ring.errors.count, "error") %> prohibited this ring from being saved:</h2>

      <ul>
      <% ring.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rings/edit.html.erb
<h1>Editing Ring</h1>

<%= render 'form', ring: @ring %>

<%= link_to 'Show', @ring %> |
<%= link_to 'Back', rings_path %>

app/views/rings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rings.each do |ring| %>
      <tr>
        <td><%= ring.name %></td>
        <td><%= link_to 'Show', ring %></td>
        <td><%= link_to 'Edit', edit_ring_path(ring) %></td>
        <td><%= link_to 'Destroy', ring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ring', new_ring_path %>

app/views/rings/new.html.erb
<h1>New Ring</h1>

<%= render 'form', ring: @ring %>

<%= link_to 'Back', rings_path %>

app/views/rings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ring.name %>
</p>

<%= link_to 'Edit', edit_ring_path(@ring) %> |
<%= link_to 'Back', rings_path %>